# Site settings
author: Pancho Labrador Jr.
title: SyntaxError
header-img: img/home-bg.png
email: plabradorjr@gmail.com
copyright_name: Pancho Labrador Jr.
description: > # this means to ignore newlines until "baseurl:"
  When you open a bag of chips and there are only 6.5 chips inside
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  plabradorjr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
